modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "sdmtoolkit"
version = "${version}"
displayName = "SDMToolkit"
authors = "Sixik"
description = '''
 Improved version of SDM Core 
'''
#logoFile = ""

[[dependencies.sdmtoolkit]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdmtoolkit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdmtoolkit]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
